### ISSUE TITLE
Uncertain of format of Multi-PIE_Aligned/A_MultiPIE.mat

### ISSUE THREAD

**Issue by sfarthin** [mihaelacr/pydeeplearn#17]
I have the Multi-PIE dataset, but the code seems to be referring to Multi-PIE_Aligned/A_MultiPIE.mat which did not come with the dataset (I only have the raw image files). Do you happen to have the code to produce the .mat file ?

**Comment by mihaelacr** [comment]
HI!

I actually do not have the code because that is how I got the database. I think that is pretty easy to write your own script in the same format if you look at the code [here](https://github.com/mihaelacr/pydeeplearn/blob/master/code/read/readfacedatabases.py#L83). The .mat file just arranges the pictures per subject, picture pose and lightning into a tensor variable.

Unfortunately I cannot do this for you as I do not have the dataset as I do not have the raw images but feel free to send a pull requests which does the reading.

Thanks!

**Comment by sfarthin** [comment]
In the [code you reference](https://github.com/mihaelacr/pydeeplearn/blob/master/code/read/readfacedatabases.py#L83), there is an option to show the image ( line 106 ). If you could snap a screenshot of one of these images (like I have below), then I'll be able to confirm that I am formatting them correctly. I'm not sure if the images are cropped on the face or anti-aliased when resized, but if you provide an example image I'll be able to quickly confirm.
[
![screen shot 2016-03-21 at 11 09 52 am](https://cloud.githubusercontent.com/assets/516498/13923070/7b7f90ca-ef55-11e5-8640-5c50434f9407.png)
](url)

Code to format image for mat file.
> from scipy.misc import imread
> from scipy.misc import imresize
> img = imread(multipie_base+"/data/session01/multiview/001/01/14_0/001_01_01_140_05.png", 1)
> img = imresize(img, (30, 40))
> data = scipy.array([ scipy.array([ scipy.array([ scipy.array([  img.reshape(-1)  ]) ]) ]) ])

**Comment by sfarthin** [comment]
nevermind, i see from your report, all the images are cropped on the face.
