### ISSUE TITLE
Multiface emotions

### ISSUE THREAD

**Issue by crankdaworld** [mihaelacr/pydeeplearn#8]
Hi,
I have seen your video demo. Just wanted to check, if your app can get emotions state of multiple people together?

Txs

**Comment by mihaelacr** [comment]
Hey. No, I have no tried that yet, but it could be done. I use open CV to detect the face and then pass the cropped face into a neural network. My current assumption was that there will only be a face in the video, but if you can use open CV in order to detect multiple faces in a frame of the video and then pass each of the faces into the neural network in order to get the emotions for each face. 

Sorry for the late reply.
